language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t arukulka/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true arukulka/docker-react npm run test
